### PR TITLE
Moving readme to profile to display this in org details page

### PR DESCRIPTION
**Pull request by kchandra548**
Based on the following suggestion, adding readme under profile folder
image

### CODE REVIEW

**Comment by vinaykanamarlapudi** [comment]
If README is moved to profile, I believe it is doesn't load when a user visit https://github.com/actions-on-packages/.github right?

**Comment by kchandra548** [comment]
For now I just copied the content but we need to move the README.
Yes it won't load if we move, but that is the special purpose of .github repo to have a readme at Org level right?

**Comment by vinaykanamarlapudi** [comment]
If README is in two places, we might end up updating two times if any change is needed. Is there any way to add a symbolic link to satisfy this requirement.

**Comment by kchandra548** [comment]
Added symbolic link, @vinaykanamarlapudi can you pls check now

**Comment by vinaykanamarlapudi** [comment]
I m not able to check , but i can approve as long as the link is not changed

**Review by vinaykanamarlapudi — APPROVED** [review]

**Pull request merged**
